name: 'hello world'

on: 
  push:
    branches:
     -  main
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: PR info
              run: | 
                echo "PR title: ${{ github.event.pull_request.title }}"
                echo "PR body: ${{ github.event.pull_request.body }}"
                echo "From branch: ${{ github.event.pull_request.head.ref }}"
                echo " To branch: ${{ github.event.pull_request.base.ref }}""