name: 'hello world'

on: 
  push:
    branches:
     -  main
jobs:
    hello-world:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "Hello world"
                echo "namaste duniya"
              name: Hello world steps
            - name: printing environment variables
              run: printenv
