name: 'hello world'

on: 
  workflow_dispatch:
  pull_request:
    branches:
      main

jobs:
    hello-world:
        runs-on: self hosted
        steps:
            - name: PR info
              run: | 
                 echo "Hello World"
                 echo " namaste duniya!"
            - name: printing environment variables
              run: printenv