name: multi job demo
on: 
  workflow_dispatch:
jobs:
    jobA:
      runs-on: ubuntu-latest
      outputs:
        rinku: ${{ steps.joba.outputs.tag }}
      steps:
        - name: jobA
          id: joba
          run: |
           echo "generating tag for docker"
           echo "tag=1.0.0" >> $GITHUB_OUTPUT


    jobB:
        runs-on: ubuntu-latest
        needs: jobA

        steps:
            - name: jobB
              run: |
               echo "jobB is running"
               echo "tag from jobA: ${{ needs.jobA.outputs.rinku }}"
