name: demo of variable and parmeters
on:
    workflow_dispatch:
env:
  name: "RAM"
  environment: "DEV"
   
jobs:
    variable-parameters:
        runs-on: ubuntu-latest
        steps:
          - name: demo of varaible and parameters
            run: |
              echo "Name: ${{ env.name }}"
              echo "Environment: ${{ env.environment }}"
          - name: variable from actions
            run: |
                 echo "This is variable from actions: ${{ VARS.ID }}"
          - name: secret using docker login
            run: |
              echo ${{ secrets.REGPASS }} | docker login --username ${{ secrets.REGUSER }} --password-stdin  git.mevijay.dev