name: demo of variable and parmeters
on:
    workflow_dispatch:
      inputs:
        environment:
          description: 'Environment to deploy'
          required: true
          default: 'DEV'
env:
  name: "RAM"
  environment: "${{ inputs.environment }}"
   
jobs:
    variable-parameters:
        runs-on: gh-agent
        steps:
          - name: demo of varaible and parameters
            run: |
              echo "Name: ${{ env.name }}"
              echo "Environment: ${{ env.environment }}"
          - name: variable from actions
            run: |
                 echo "This is variable from actions: ${{ VARS.ID }}"
          - name: secret using docker login
            run: |
              echo ${{ secrets.REGPASS }} | docker login --username ${{ secrets.REGUSER }} --password-stdin  ${{ vars.ART_URL }}